spring:
  application:
    name: report-rendering-api

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: Report Rendering API
    description: REST API for generating financial reports in multiple formats (HTML, CSV, PDF)
    version: 1.0.0
    contact:
      name: TVM Software
      email: igormusic@tvmsoftware.com
    license:
      name: MIT License

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.tvm.reportrendering: DEBUG
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.thymeleaf: DEBUG
    com.microsoft.playwright: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/report-rendering-api.log