name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.50.0-noble

    strategy:
      matrix:
        java-version: [17, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Java and Maven
      run: |
        apt-get update
        apt-get install -y openjdk-${{ matrix.java-version }}-jdk maven curl
        apt-get clean && rm -rf /var/lib/apt/lists/*

    - name: Set JAVA_HOME
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-${{ matrix.java-version }}-openjdk-amd64" >> $GITHUB_ENV
        echo "/usr/lib/jvm/java-${{ matrix.java-version }}-openjdk-amd64/bin" >> $GITHUB_PATH

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Validate Maven project
      run: mvn validate

    - name: Compile project
      run: mvn clean compile

    - name: Run tests
      run: mvn test

    - name: Generate test report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests (JDK ${{ matrix.java-version }})
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
        fail-on-empty: false

    - name: Package application
      run: mvn package -DskipTests

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-jdk-${{ matrix.java-version }}
        path: |
          target/surefire-reports/
          target/*.jar

    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      if: matrix.java-version == '17'
      with:
        file: target/site/jacoco/jacoco.xml
        fail_ci_if_error: false